### ISSUE TITLE
Request: simplex-chat cli

### ISSUE THREAD

**Issue by Azathothas** [leleliu008/ppkg-formula-repository-official-core#6]
Recently I got a request to add [simplex-chat cli](https://github.com/simplex-chat/simplex-chat/blob/stable/docs/CLI.md) at: https://github.com/Azathothas/Toolpacks/issues/34

The dockerfile for building it: https://github.com/simplex-chat/simplex-chat/blob/2abee7edf8cd1c975c9336aa7885f6f818b88d7e/Dockerfile

However, mine fails when I try to build it. 
I have no experience in building Haskell apps.
I would highly appreciate it if you could take a look, Thanks!

**Comment by leleliu008** [comment]
I will look into it.

**Comment by leleliu008** [comment]
by the way, I updated the ndk-pkg and it's formula repository yesterday, but I cann't push the docker image to `docker.io` due to the chinese government has blocked it recently, I do not plan to update the `fpliu/ndk-pkg` containner image any more. if you use it , please do `ndk-pkg upgrade-self`, otherwize you might face problems.

**Comment by leleliu008** [comment]
you don not need to run `ndk-pkg upgrade-self` when building your docker image. because you fetch from github, it's always the latest.

I found you fetch from dev branch https://raw.githubusercontent.com/leleliu008/ndk-pkg/dev/ndk-pkg , master is recommanded.

you don not need to run `ndk-pkg formula-repo-sync "official-core"` when building your docker image, `ndk-pkg setup` already do it for you.

you don not need to run install glibc in alpine linux, `ndk-pkg setup` already do it for you. https://github.com/leleliu008/ndk-pkg/blob/master/ndk-pkg#L8552C1-L8555

**Comment by leleliu008** [comment]
```bash
wget https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/ndk-pkg
chmod +x ndk-pkg
./ndk-pkg setup
./ndk-pkg install
```

`ndk-pkg setup` is mainly doing the following things:

install `tar`, `xz`, `g++`, `gcompat`, `linux-headers` commands via your system's package manager

install [uppm](https://github.com/leleliu008/uppm) to ~/.ndk-pkg/core

install other essential tools (listed below) that are used by this shell script via [uppm](https://github.com/leleliu008/uppm)

[GNU Bash](https://www.gnu.org/software/bash/manual/bash.html)
[GNU CoreUtils](https://www.gnu.org/software/coreutils/manual/coreutils.html)
[GNU FindUtils](https://www.gnu.org/software/findutils/manual/html_mono/find.html)
[GNU awk](https://www.gnu.org/software/gawk/manual/gawk.html)
[GNU sed](https://www.gnu.org/software/sed/manual/sed.html)
[GNU grep](https://www.gnu.org/software/grep/manual/grep.html)
[BSD tar](https://man.archlinux.org/man/core/libarchive/bsdtar.1.en)
[patchelf](https://github.com/NixOS/patchelf)
[sysinfo](https://github.com/leleliu008/C-examples/tree/master/utils/sysinfo)
[tree](https://linux.die.net/man/1/tree)
[curl](https://curl.se/docs/manpage.html)
[git](https://git-scm.com/docs/git)
[xxd](https://raw.githubusercontent.com/vim/vim/master/runtime/doc/xxd.man)
[fzf](https://github.com/junegunn/fzf)
[bat](https://github.com/sharkdp/bat)
[jq](https://stedolan.github.io/jq/manual/)
[yq](https://mikefarah.gitbook.io/yq/)
[d2](https://github.com/terrastruct/d2)

**Comment by Azathothas** [comment]
I haven't checked ndk-pkg in a while and when I wrote that dockerfile, all those steps were necessary.
ndk-pkg also required glibc and didn't work on alpine out of the box.
It's good to see that it now support most of the things by itself.
I have updated the dockerfile to install from master & disabled the glibc part.
Thank you for the suggestion.

**Comment by leleliu008** [comment]
done. https://github.com/leleliu008/ppkg-formula-repository-official-core/blob/master/formula/simplex-chat.yml

**Comment by Azathothas** [comment]
Yes, sorry I got busy and forgot about this.
Thank you
